### ISSUE TITLE
option 2 of full pipeline

### ISSUE THREAD

**Issue by smith6jt-cop** [murphygroup/CellSegmentationEvaluator#10]
there is no img_dir prompt and my .tif file in the full_pipeline folder is not recognized

**Comment by smith6jt-cop** [comment]
problem occurs with any option after: python run_pipeline.py ./config.json

Traceback (most recent call last):
  File "/home/smith6jt/CellSegmentationEvaluator/full_pipeline/run_pipeline.py", line 5, in <module>
    pipeline.argparse_wrapper()
  File "/home/smith6jt/CellSegmentationEvaluator/full_pipeline/pipeline/pipeline.py", line 68, in argparse_wrapper
    main(args.config_dir)
  File "/home/smith6jt/CellSegmentationEvaluator/full_pipeline/pipeline/pipeline.py", line 25, in main
    img_dirs = [config['img_dir']]
KeyError: 'img_dir'

**Comment by rfmurphy** [comment]
See issue "Dependencies for full pipeline"
